### ISSUE TITLE
Blender glitches

### ISSUE THREAD

**Issue by krogala** [pedro00dk/nvidia-exec#10]
Hi Guys,

I have to say that I am super impressed with nvidia-exec. This is the first time for me that an nvidia switching software works right out of the box without any manual configuration!

The only challenge that I have encountered though — is with Blender. There are major graphical glitches that I am not sure how to solve — please see the two attached images: with and without running nvx.

```
nvx start blender
# turn on gpu
-- pci rescan
-- pci "PCI bridge - JHL6540 Thunderbolt 3 Bridge (C step) [Alpine Ridge 4C 2016]" -> 0000:02:01.0
   -- pci power control on
   -- device enable "VGA compatible controller - GA102 [GeForce RTX 3080 Ti]" -> 0000:03:00.0
# load modules
   -- module nvidia
   -- module nvidia_uvm
   -- module nvidia_modeset
   -- module nvidia_drm
Read prefs: /home/ymir/.config/blender/3.1/config/userpref.blend
Saved session recovery to '/tmp/quit.blend'
```

Any help would be greatly appreciated!

WITHOUT NVX:
![Screenshot from 2022-04-25 00-26-29](https://user-images.githubusercontent.com/37286209/165021087-57675e56-9d28-42d5-a557-a6aad6258cbe.png)

WITH NVX:
![Screenshot from 2022-04-25 00-25-59](https://user-images.githubusercontent.com/37286209/165021090-181c4043-f801-445d-9e45-5ea2c88f03ef.png)

**Comment by CygnusTerminal** [comment]
HI, i am having the same kind of issues running Steam, with disappearing parts of the screen.

**Comment by pedro00dk** [comment]
Hey @krogala  and @CygnusTerminal 

I was able to reproduce the blender issue, but only when using Wayland, Xorg worked fine. Could you please try running it using Xorg?
Unfortunately, I do not think this is a thing I am able to solve. I believe that depends on the Nvidia driver support.

About steam, I was not able to reproduce the issue, when using Wayland, I get some blinking menu popups on Wayland, but nothing more than that. On Xorg it works perfectly. I believe that is the same issue as well, but I do not know how to solve it. (besides changing the display server)

**Comment by krogala** [comment]
Thanks @pedro00dk. Indeed, it looks like Blender works in Xorg a little bit better than in Wayland. But there are still some glitches remaining. I am now able to do some work using Xorg though, so thanks for the tip!

Do you think this issue is on the nvidia-exec side, or on the driver side? Perhaps it might be worth mentioning this issue to driver developers?

**Comment by pedro00dk** [comment]
The technology that allows turning off the GPU on Linux is somewhat recent, and better support for Wayland is being worked on in recent NVidia driver versions.
So I would suppose this is on the driver's side, but I may be wrong.

**Comment by pedro00dk** [comment]
Hi @krogala .
I tested blender again on wayland with the newer Nvidia drivers and had a different result than before.
It is now "working". Sometimes the window gest black but it fixes itself when I resize it. There are other minor glitches, but much minor that the ones we had before.
I just want to check if the same is happening with you.

**Comment by pedro00dk** [comment]
It seems that the situation is improving with newer NVidia drivers. That makes me more confident that the issue was on the driver side.
