### ISSUE TITLE
Unable to Connect to External Monitor

### ISSUE THREAD

**Issue by aflyingpumpkin** [pedro00dk/nvidia-exec#25]
When I run `xrandr --auto --verbose` after plugging in the monitor I get the following error:
```sh
crtc 4:    1920x1080  60.00 +0+0 "HDMI-1-0"
xrandr: Configure crtc 4 failed
crtc 0: disable
crtc 1: disable
crtc 2: disable
crtc 3: disable
crtc 4: disable
crtc 5: disable
crtc 6: disable
crtc 7: disable
screen 0: revert
crtc 0: revert
crtc 1: revert
crtc 2: revert
crtc 3: revert
crtc 4: revert
crtc 5: revert
crtc 6: revert
crtc 7: revert
```
The monitor is recognized by Gnome Settings, but when I try to connect it nothing happens.
When on Wayland the display does not appear in Gnome Settings.

System Info:
```
CPU: Ryzen9 6900HX
GPU: RTX3070Ti
Distro: Arch
Display Server: X11
Relevant Kernel Parameters: nvidia_drm modeset=1 (though I still had the issue when these were not set)
```

How should I go about further debugging / fixing this?

**Comment by taylor85345** [comment]
On a laptop, HDMI ports are usually routed through the external GPU, which is being disabled by nvx. You will need to enable the GPU via `nvx on` before it your ports will work. You may also need to sign out of any existing desktop session and sign back in before the connected monitor will be detected.

**Comment by BenMac31** [comment]
Thanks, it has begun working.

**Comment by 41Leahcim** [comment]
I have the same problem, but without error message.
System info:
```
CPU: Intel(R) Core(TM) i7-10750H
GPU: GeForce RTX 2070 Mobile / Max-Q Refresh
Distro: Arch
Display Server: Gnome/Wayland
```

I have already turned my gpu on and signed out and back in, but it still doesn't work.

**Comment by MathisP75** [comment]
Same issue for me on Hyprland. `nvx-status` reports `on`, but `nvidia-smi -q` reports
```
    Display Mode                          : Enabled
    Display Active                        : Disabled
```
