### ISSUE TITLE
AUR PKGBUILD is out of date

### ISSUE THREAD

**Issue by lurker98** [pedro00dk/nvidia-exec#30]
The AUR package has not been update with a new PKGBUILD to install version 1.1
I believe this should be a simple fix of editing a few lines

https://aur.archlinux.org/packages/nvidia-exec

**Comment by pedro00dk** [comment]
Hey @lurker98,

v0.1.1 is a broken version, it it was an attempt to keep GPU state during suspend, but it is broken.
Currently, I'm without an nvidia hibrid laptop in order to test and fix it.

**Comment by lurker98** [comment]
Hello Mr. Henrique,

I have an NVIDIA hybrid laptop. Would you like to maybe run your code on
mine?
I could let you. I run endeavourOS.
