### ISSUE TITLE
How to install on Ubuntu 23.04

### ISSUE THREAD

**Issue by aisivan36** [pedro00dk/nvidia-exec#31]
Any guide how to install on Ubuntu?, as I don't currently use Arch Linux.

**Comment by lurker98** [comment]
@aisivan36  This package is highly experimental and only works on Arch Linux.

**Comment by pedro00dk** [comment]
You can probably put the scripts in the proper directories for your distro and verify if all dependencies are available and it should work just fine. However, I don't use other distros, I don't know how to package for ubuntu.
