### ISSUE TITLE
lshw update on Arch

### ISSUE THREAD

**Issue by x140x1n** [pedro00dk/nvidia-exec#35]
After the update of lshw on Arch to package version B.02.19.2-6 nvidia-exec no longer works due to the change of output from lshw.

on last version  B.02.19.2-5 the output was :
 {
        "id" : "pci:0",
        "class" : "bridge",
        "claimed" : true,
        "handle" : "PCIBUS:0000:01",
        "description" : "PCI bridge",
        "product" : "Sunrise Point-LP PCI Express Root Port #1",
        "vendor" : "Intel Corporation",
        "physid" : "1c",
        "businfo" : "pci@0000:00:1c.0",
        "version" : "f1",
        "width" : 32,
        "clock" : 33000000,
        "configuration" : {
          "driver" : "pcieport"
        },
        "capabilities" : {
          "pci" : true,
          "normal_decode" : true,
          "bus_master" : "bus mastering",
          "cap_list" : "PCI capabilities listing"
        },
        "children" : [
          {
            "id" : "display",
            "class" : "display",
            "claimed" : true,
            "handle" : "PCI:0000:01:00.0",
            "description" : "3D controller",
            "product" : "GP108M [GeForce MX150]",
            "vendor" : "NVIDIA Corporation",
            "physid" : "0",
            "businfo" : "pci@0000:01:00.0",
            "version" : "a1",
            "width" : 64,
            "clock" : 33000000,
            "configuration" : {
              "driver" : "nvidia",
              "latency" : "0"
            },
            "capabilities" : {
              "bus_master" : "bus mastering",
              "cap_list" : "PCI capabilities listing",
              "rom" : "extension ROM"
            }
          }
        ]
      }

and on the upgraded version the output is like this:

{
        "id" : "pci:0",
        "class" : "bridge",
        "claimed" : true,
        "handle" : "PCIBUS:0000:01",
        "description" : "PCI bridge",
        "product" : "Sunrise Point-LP PCI Express Root Port #1",
        "vendor" : "Intel Corporation",
        "physid" : "1c",
        "businfo" : "pci@0000:00:1c.0",
        "version" : "f1",
        "width" : 32,
        "clock" : 33000000,
        "configuration" : {
          "driver" : "pcieport"
        },
        "capabilities" : {
          "pci" : true,
          "pciexpress" : "PCI Express",
          "msi" : "Message Signalled Interrupts",
          "pm" : "Power Management",
          "normal_decode" : true,
          "bus_master" : "bus mastering",
          "cap_list" : "PCI capabilities listing"
        }
      },
          {
            "id" : "display",
            "class" : "display",
            "claimed" : true,
            "handle" : "PCI:0000:01:00.0",
            "description" : "3D controller",
            "product" : "GP108M [GeForce MX150]",
            "vendor" : "NVIDIA Corporation",
            "physid" : "0",
            "businfo" : "pci@0000:01:00.0",
            "version" : "a1",
            "width" : 64,
            "clock" : 33000000,
            "configuration" : {
              "driver" : "nvidia",
              "latency" : "0"
            },
            "capabilities" : {
              "pm" : "Power Management",
              "msi" : "Message Signalled Interrupts",
              "pciexpress" : "PCI Express",
              "bus_master" : "bus mastering",
              "cap_list" : "PCI capabilities listing",
              "rom" : "extension ROM"
            }
          },

For now I have downgraded lshw to make nvidia-exec work again.

**Comment by Dronte** [comment]
The fix is proposed in https://github.com/lyonel/lshw/pull/88

**Comment by pedro00dk** [comment]
Fixed, a new version 0.1.2 is now available on AUR.
