### ISSUE TITLE
Turing support?

### ISSUE THREAD

**Issue by CygnusTerminal** [pedro00dk/nvidia-exec#6]
Hi, nvx looks like a promising software for managing nvidia cards on Linux. I am eager to test it, but i see that there is no support for Turing cards. Will it work anyway? Can i help adding support for Turing cards (i can test it and report bugs, sadly i'm no programmer). Hope this does not bother. 
Cheers.

**Comment by pedro00dk** [comment]
Hi @CygnusTerminal,

I do not have a Turing card, but I think it is going to work fine.

**Comment by pedro00dk** [comment]
I'm going to track this last issue you mentioned on https://github.com/pedro00dk/nvidia-exec/issues/7
