### ISSUE TITLE
It does not work after first reboot

### ISSUE THREAD

**Issue by lfom** [pedro00dk/nvidia-exec#9]
Hello, there!

Thank you for creating and maintaining nvidia-exec. It seems to work right after installation, but not once I restart the computer: the nvidia kernel modules cannot be loaded anymore.

I noticed there was a nvx.conf file that blacklists the modules, and disabling it seems to fix the problem. Is the conf file necessary as the systemd service disables the modules during boot or I am missing something?

I'm using Garuda/Arch and Gnome on Wayland as DE, latest 510.x drivers for a MX350 chip. Please feel free to ask for more info if needed.

Regards

**Comment by pedro00dk** [comment]
Hi @lfom!

Thanks for reporting the issue.
I just wanted to ensure the modules are not going to be loaded during boot. It worked the first time for me so I did not tinker too much with it.
I'm going to test that case and also try disabling the modules in the boot script as well to check what happens.
